### ISSUE TITLE
How can i deploy on firebase

### ISSUE THREAD

**Issue by OmarioHasan** [Angular-RU/angular-universal-starter#244]
I'm trying to use ng deploy but failed to host the SSR Version
But got `Source and destination must not be the same.`

**Comment by Gorniv** [comment]
firebase is not good hosting for the node server project

**Comment by OmarioHasan** [comment]
@Gorniv  it that the solution , you just closed the issue and told me there is no solution ?

**Comment by Gorniv** [comment]
use prerender and deploy statics HTML =) or use cloud VPS. 
I am deploying to kubernetes with docker

**Comment by ribomation** [comment]
@OmarioHasan, My site is deployed to Firebase Hosting and it's Angular v9 with SSR using the ExpressJS engine. 

However, I do not use the `ng deploy` command, because IMO it's pointless when you already have the firebase-tools installed. Just use the command `firebase deploy` command.

Before deploying, you need to configure firebase for hosting both the static assets from `ng build --prod` but also the result of building the SSR express engine. That latter should be configured as a firebase cloud function and all trafic (except CSS, JPG, ...) should be redirected to that function. 

Here is the link to my site: https://www.ribomation.com/home

**Comment by OmarioHasan** [comment]
@ribomation  can you show your configurations and the steps you do , i will be also glade if you support me with a repo that i can use
